# Generated by Django 2.0.6 on 2018-06-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180626_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='上传产品展示图片'),
        ),
    ]
