# Generated by Django 2.0.6 on 2018-06-24 15:59

from django.db import migrations, models
import extra_apps.DjangoUeditor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('info', models.CharField(blank=True, max_length=500, null=True, verbose_name='商品描述')),
                ('detail', extra_apps.DjangoUeditor.models.UEditorField(default='', verbose_name='商品详情')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'goods',
            },
        ),
    ]
