# Generated by Django 2.0.6 on 2018-06-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='add_time',
            field=models.DateField(blank=True, null=True, verbose_name='添加时间'),
        ),
    ]
