# Generated by Django 2.0.6 on 2018-06-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180624_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='add_time',
        ),
    ]
