# Generated by Django 2.0.6 on 2018-06-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZBList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='指标名称')),
                ('type', models.CharField(choices=[('ggzb', '感官指标'), ('jbyy', '基本营养指标'), ('tyxyy', '特异性营养指标'), ('dnatp', 'DNA图谱'), ('cdhj', '产地环境')], default='ggzb', max_length=20, verbose_name='指标类型')),
                ('info', models.CharField(blank=True, max_length=200, null=True, verbose_name='指标描述')),
            ],
            options={
                'verbose_name': '指标',
                'verbose_name_plural': '指标',
                'db_table': 'zb_list',
            },
        ),
    ]
