# Generated by Django 2.0.6 on 2018-06-22 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product'),
        ('zb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZBValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='指标值')),
                ('avg_range', models.IntegerField(choices=[(1, '平均值'), (2, '范围')], default=1, verbose_name='平均-范围')),
                ('info', models.CharField(blank=True, max_length=200, null=True, verbose_name='指标值描述')),
                ('product', models.ForeignKey(on_delete='产品', to='products.Product')),
                ('zb_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zb.ZBList', verbose_name='指标')),
            ],
            options={
                'verbose_name': '指标值',
                'verbose_name_plural': '指标值',
                'db_table': 'zb_value',
            },
        ),
    ]
