# Generated by Django 2.0.6 on 2018-06-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zb', '0002_zbvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zbvalue',
            name='product',
            field=models.ForeignKey(on_delete='产品', to='products.Product', verbose_name='产品'),
        ),
    ]
