# Generated by Django 2.0.6 on 2018-06-23 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180622_1907'),
        ('zb', '0004_auto_20180623_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDHJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='指标值')),
                ('avg_range', models.IntegerField(choices=[(1, '平均值'), (2, '范围')], default=1, verbose_name='平均-范围')),
                ('info', models.CharField(blank=True, max_length=200, null=True, verbose_name='指标值描述')),
                ('product', models.ForeignKey(on_delete='产品', to='products.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产地环境',
                'verbose_name_plural': '产地环境',
                'db_table': 'zb_cdhj',
            },
        ),
        migrations.CreateModel(
            name='DNATP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='指标值')),
                ('avg_range', models.IntegerField(choices=[(1, '平均值'), (2, '范围')], default=1, verbose_name='平均-范围')),
                ('info', models.CharField(blank=True, max_length=200, null=True, verbose_name='指标值描述')),
                ('product', models.ForeignKey(on_delete='产品', to='products.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': 'DNA图谱',
                'verbose_name_plural': 'DNA图谱',
                'db_table': 'zb_dnatp',
            },
        ),
        migrations.CreateModel(
            name='GGZB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='指标值')),
                ('avg_range', models.IntegerField(choices=[(1, '平均值'), (2, '范围')], default=1, verbose_name='平均-范围')),
                ('info', models.CharField(blank=True, max_length=200, null=True, verbose_name='指标值描述')),
                ('product', models.ForeignKey(on_delete='产品', to='products.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '感官指标',
                'verbose_name_plural': '感官指标',
                'db_table': 'zb_gg',
            },
        ),
        migrations.CreateModel(
            name='JBYYZB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='指标值')),
                ('avg_range', models.IntegerField(choices=[(1, '平均值'), (2, '范围')], default=1, verbose_name='平均-范围')),
                ('info', models.CharField(blank=True, max_length=200, null=True, verbose_name='指标值描述')),
                ('product', models.ForeignKey(on_delete='产品', to='products.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '基本营养指标',
                'verbose_name_plural': '基本营养指标',
                'db_table': 'zb_jbyy',
            },
        ),
        migrations.CreateModel(
            name='TYXYYZB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='指标值')),
                ('avg_range', models.IntegerField(choices=[(1, '平均值'), (2, '范围')], default=1, verbose_name='平均-范围')),
                ('info', models.CharField(blank=True, max_length=200, null=True, verbose_name='指标值描述')),
                ('product', models.ForeignKey(on_delete='产品', to='products.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '特异性营养指标',
                'verbose_name_plural': '特异性营养指标',
                'db_table': 'zb_tyxyy',
            },
        ),
        migrations.AlterModelOptions(
            name='zblist',
            options={'verbose_name': '新增指标', 'verbose_name_plural': '新增指标'},
        ),
        migrations.AddField(
            model_name='tyxyyzb',
            name='zb_list',
            field=models.ForeignKey(limit_choices_to={'type': 'tyxyy'}, on_delete=django.db.models.deletion.CASCADE, to='zb.ZBList', verbose_name='指标'),
        ),
        migrations.AddField(
            model_name='jbyyzb',
            name='zb_list',
            field=models.ForeignKey(limit_choices_to={'type': 'jbyy'}, on_delete=django.db.models.deletion.CASCADE, to='zb.ZBList', verbose_name='指标'),
        ),
        migrations.AddField(
            model_name='ggzb',
            name='zb_list',
            field=models.ForeignKey(limit_choices_to={'type': 'ggzb'}, on_delete=django.db.models.deletion.CASCADE, to='zb.ZBList', verbose_name='指标'),
        ),
        migrations.AddField(
            model_name='dnatp',
            name='zb_list',
            field=models.ForeignKey(limit_choices_to={'type': 'dnatp'}, on_delete=django.db.models.deletion.CASCADE, to='zb.ZBList', verbose_name='指标'),
        ),
        migrations.AddField(
            model_name='cdhj',
            name='zb_list',
            field=models.ForeignKey(limit_choices_to={'type': 'cdhj'}, on_delete=django.db.models.deletion.CASCADE, to='zb.ZBList', verbose_name='指标'),
        ),
    ]
