# Generated by Django 2.0.6 on 2018-06-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zb', '0005_auto_20180623_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zbvalue',
            name='product',
        ),
        migrations.RemoveField(
            model_name='zbvalue',
            name='zb_list',
        ),
        migrations.DeleteModel(
            name='ZBValue',
        ),
    ]
