# Generated by Django 2.0.6 on 2018-06-28 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_auto_20180626_1422'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commodity',
            table='commodity',
        ),
    ]
