# Generated by Django 2.0.6 on 2018-06-28 11:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
import extra_apps.DjangoUeditor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='信息名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='information/', verbose_name='上传展示图片')),
                ('info', models.CharField(blank=True, max_length=500, null=True, verbose_name='信息描述')),
                ('detail', extra_apps.DjangoUeditor.models.UEditorField(default='', verbose_name='信息详情')),
            ],
            options={
                'verbose_name': '信息',
                'verbose_name_plural': '信息',
                'db_table': 'Information',
            },
        ),
        migrations.CreateModel(
            name='InformationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='信息类型')),
                ('info', models.CharField(blank=True, max_length=500, null=True, verbose_name='信息类型描述')),
            ],
            options={
                'verbose_name': '信息类型',
                'verbose_name_plural': '信息类型',
                'db_table': 'InformationType',
            },
        ),
        migrations.AddField(
            model_name='information',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.InformationType', verbose_name='信息类型'),
        ),
    ]
