# Generated by Django 2.0.6 on 2018-06-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='publisher',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='信息名称'),
        ),
    ]
