# Generated by Django 2.0.6 on 2018-06-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_information_publisher'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='information',
            table='information',
        ),
        migrations.AlterModelTable(
            name='informationtype',
            table='information_type',
        ),
    ]
