# Generated by Django 2.0.6 on 2018-06-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_auto_20180628_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='publisher',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='发布人'),
        ),
    ]
